<?php

declare(strict_types=1);

namespace App\Core\Extension;

final class ExtensionMessageKey
{
    public const EXTENSION_MANIFEST_UNREADABLE = 'message.extension.manifest_unreadable';
    public const EXTENSION_REQUIRED_FILE_MISSING = 'message.extension.required_file_missing';
    public const EXTENSION_REQUIRED_DIRECTORY_MISSING = 'message.extension.required_directory_missing';
    public const EXTENSION_FILE_UNREADABLE = 'message.extension.file_unreadable';
    public const EXTENSION_PHP_SYNTAX_ERROR = 'message.extension.php_syntax_error';
    public const EXTENSION_PHP_NAMESPACE_INVALID = 'message.extension.php_namespace_invalid';
    public const EXTENSION_TWIG_SYNTAX_ERROR = 'message.extension.twig_syntax_error';
    public const EXTENSION_TRANSLATION_FALLBACK_MISSING = 'message.extension.translation_fallback_missing';
    public const EXTENSION_TRANSLATION_NAMESPACE_INVALID = 'message.extension.translation_namespace_invalid';
    public const EXTENSION_JSON_SYNTAX_ERROR = 'message.extension.json_syntax_error';
    public const EXTENSION_YAML_SYNTAX_ERROR = 'message.extension.yaml_syntax_error';
    public const EXTENSION_CSS_SYNTAX_ERROR = 'message.extension.css_syntax_error';
    public const EXTENSION_CSS_NAMESPACE_INVALID = 'message.extension.css_namespace_invalid';
    public const EXTENSION_JAVASCRIPT_SYNTAX_ERROR = 'message.extension.javascript_syntax_error';
    public const EXTENSION_SCOPE_INVALID = 'message.extension.scope_invalid';
    public const EXTENSION_TEMPLATE_PATH_INVALID = 'message.extension.template_path_invalid';
    public const EXTENSION_TEMPLATE_REFERENCE_INVALID = 'message.extension.template_reference_invalid';
    public const EXTENSION_POLICY_BLOCKED_PATH = 'message.extension.policy.blocked_path';
    public const EXTENSION_POLICY_WARNED_PATH = 'message.extension.policy.warned_path';
    public const EXTENSION_POLICY_BLOCKED_PHP_CAPABILITY = 'message.extension.policy.blocked_php_capability';
    public const EXTENSION_COPY_SOURCE_MISSING = 'message.extension.copy_source_missing';
    public const EXTENSION_COPY_SOURCE_SYMLINK = 'message.extension.copy_source_symlink';
    public const EXTENSION_ASSET_SYNC_COMPLETED = 'message.extension.asset_sync_completed';
    public const EXTENSION_ASSET_SYNC_FAILED = 'message.extension.asset_sync_failed';
    public const EXTENSION_ASSET_REBUILD_QUEUED = 'message.extension.asset_rebuild_queued';
    public const EXTENSION_ASSET_REBUILD_QUEUE_FAILED = 'message.extension.asset_rebuild_queue_failed';
    public const EXTENSION_ASSET_CONTRIBUTION_EXTENSION_INVALID = 'message.extension.asset.contribution_extension_invalid';
    public const EXTENSION_ASSET_CONTRIBUTION_TYPE_INVALID = 'message.extension.asset.contribution_type_invalid';
    public const EXTENSION_ASSET_CONTRIBUTION_PATH_INVALID = 'message.extension.asset.contribution_path_invalid';
    public const EXTENSION_ASSET_CONTRIBUTION_PATH_TRAVERSAL = 'message.extension.asset.contribution_path_traversal';
    public const EXTENSION_DISCOVERY_QUEUED = 'message.extension.discovery_queued';
    public const EXTENSION_DISCOVERY_QUEUE_FAILED = 'message.extension.discovery_queue_failed';
    public const EXTENSION_DISCOVERY_COMPLETED = 'message.extension.discovery_completed';
    public const EXTENSION_VALIDATION_COMPLETED = 'message.extension.validation_completed';
    public const EXTENSION_COPY_PLAN_CREATED = 'message.extension.copy_plan_created';
    public const EXTENSION_REGISTRY_SYNC_COMPLETED = 'message.extension.registry.sync_completed';
    public const EXTENSION_REGISTRY_EXTENSION_REGISTERED = 'message.extension.registry.registered';
    public const EXTENSION_REGISTRY_EXTENSION_UPDATED = 'message.extension.registry.updated';
    public const EXTENSION_REGISTRY_EXTENSION_REMOVED = 'message.extension.registry.removed';
    public const EXTENSION_REGISTRY_EXTENSION_FAULTY = 'message.extension.registry.faulty';
    public const EXTENSION_INSTALL_UPLOAD_INVALID = 'message.extension.install.upload_invalid';
    public const EXTENSION_INSTALL_ZIP_INVALID = 'message.extension.install.zip_invalid';
    public const EXTENSION_INSTALL_ROOT_INVALID = 'message.extension.install.root_invalid';
    public const EXTENSION_INSTALL_READY = 'message.extension.install.ready';
    public const EXTENSION_INSTALL_OVERWRITE = 'message.extension.install.overwrite';
    public const EXTENSION_INSTALL_VERSION_BLOCKED = 'message.extension.install.version_blocked';
    public const EXTENSION_INSTALL_COMPLETED = 'message.extension.install.completed';
    public const EXTENSION_LIFECYCLE_EXTENSION_NOT_FOUND = 'message.extension.lifecycle.not_found';
    public const EXTENSION_LIFECYCLE_STATUS_BLOCKED = 'message.extension.lifecycle.status_blocked';
    public const EXTENSION_LIFECYCLE_ACTIVATED = 'message.extension.lifecycle.activated';
    public const EXTENSION_LIFECYCLE_DEACTIVATED = 'message.extension.lifecycle.deactivated';
    public const EXTENSION_LIFECYCLE_DEPENDENT_DEACTIVATED = 'message.extension.lifecycle.dependent_deactivated';
    public const EXTENSION_LIFECYCLE_CLEANUP_COMPLETED = 'message.extension.lifecycle.cleanup_completed';
    public const EXTENSION_LIFECYCLE_REMOVED = 'message.extension.lifecycle.removed';
    public const EXTENSION_LIFECYCLE_PURGED = 'message.extension.lifecycle.purged';
    public const EXTENSION_LIFECYCLE_FAULT_RESET = 'message.extension.lifecycle.fault_reset';
    public const EXTENSION_LIFECYCLE_RUNTIME_FAILURE = 'message.extension.lifecycle.runtime_failure';
    public const EXTENSION_LIFECYCLE_PHP_LOAD_FAILED = 'message.extension.lifecycle.php_load_failed';
    public const EXTENSION_LIFECYCLE_ROLLED_BACK = 'message.extension.lifecycle.rolled_back';
    public const EXTENSION_RUNTIME_CONTRIBUTION_UNSUPPORTED = 'message.extension.runtime.contribution_unsupported';
    public const EXTENSION_LIVE_ENDPOINT_PATH_INVALID = 'message.extension.live.endpoint_path_invalid';
    public const EXTENSION_LIVE_ENDPOINT_HANDLER_INVALID = 'message.extension.live.endpoint_handler_invalid';
    public const EXTENSION_LIVE_ENDPOINT_RESERVED = 'message.extension.live.endpoint_reserved';
    public const EXTENSION_SETTING_READ_FAILED = 'message.extension.setting.read_failed';
    public const EXTENSION_SETTING_WRITE_FAILED = 'message.extension.setting.write_failed';
    public const EXTENSION_SETTING_DELETE_FAILED = 'message.extension.setting.delete_failed';
    public const EXTENSION_SETTING_VALUE_INVALID = 'message.extension.setting.value_invalid';
    public const EXTENSION_DEPENDENCY_MISSING = 'message.extension.dependency.missing';
    public const EXTENSION_DEPENDENCY_INVALID = 'message.extension.dependency.invalid';
    public const EXTENSION_SCHEDULER_CRON_INVALID = 'message.extension.scheduler.cron_invalid';
    public const EXTENSION_SCHEDULER_SOURCE_INVALID = 'message.extension.scheduler.source_invalid';
    public const EXTENSION_SCHEDULER_TRUSTED_BLOCKED = 'message.extension.scheduler.trusted_blocked';
    public const EXTENSION_DEPENDENCY_VERSION_UNSATISFIED = 'message.extension.dependency.version_unsatisfied';
    public const EXTENSION_DEPENDENCY_STATUS_BLOCKED = 'message.extension.dependency.status_blocked';
    public const EXTENSION_DEPENDENCY_CYCLE = 'message.extension.dependency.cycle';
    public const EXTENSION_DEPENDENCY_RESOLVED = 'message.extension.dependency.resolved';
    public const EXTENSION_IDENTIFIER_INVALID = 'message.extension.identifier.invalid';
}
