twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/templates/frontend': frontend
        '%kernel.project_dir%/templates/backend': backend
        '%kernel.project_dir%/templates': root
        '%kernel.project_dir%/templates/provider': provider

when@test:
    twig:
        strict_variables: true
