when@dev:
    web_profiler:
        toolbar: true

    framework:
        profiler:
            enabled: true
            collect: true

when@test:
    framework:
        profiler:
            collect: false
